### ISSUE TITLE
AssertionError in a race condition on a CTRL-C shutdown sometimes

### ISSUE THREAD

**Issue by ljnelson** [microbean/microbean-jersey-netty-cdi#3]
When a program using this extension is killed with `CTRL-C`, sometimes this exception stack is thrown (note the `AssertionError`), suggesting that something is up with the `shutdownLatch`:
```
Exception in thread "main" Exception in thread "Thread-2" java.lang.IllegalStateException: WELD-ENV-002002: Weld SE container 83d4e3ca-1d00-43b9-91d7-9b44c1cfced1 was already shut down
	at org.jboss.weld.environment.se.WeldContainer.checkIsRunning(WeldContainer.java:370)
	at org.jboss.weld.environment.se.WeldContainer.shutdown(WeldContainer.java:295)
	at org.jboss.weld.environment.se.WeldContainer$ShutdownHook.run(WeldContainer.java:344)
javax.enterprise.event.ObserverException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.jboss.weld.security.NewInstanceAction.run(NewInstanceAction.java:33)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:40)
	at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:78)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:103)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
	at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:168)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
	at org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:159)
	at org.jboss.weld.manager.BeanManagerImpl.fireEvent(BeanManagerImpl.java:632)
	at org.jboss.weld.environment.se.WeldContainer.shutdown(WeldContainer.java:297)
	at org.jboss.weld.environment.se.WeldContainer.close(WeldContainer.java:318)
	at org.microbean.main.Main.main(Main.java:203)
	at org.microbean.main.Main.main(Main.java:127)
Caused by: java.lang.AssertionError
	at org.microbean.jersey.netty.cdi.JerseyNettyExtension.waitForAllServersToStop(JerseyNettyExtension.java:424)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
```

**Comment by ljnelson** [comment]
We do this in the constructor of the extension:
https://github.com/microbean/microbean-jersey-netty-cdi/blob/dfb925921aee894e818a3aa55ce47571e336304d/src/main/java/org/microbean/jersey/netty/cdi/JerseyNettyExtension.java#L139-L148
…then down towards the end there is this:
https://github.com/microbean/microbean-jersey-netty-cdi/blob/dfb925921aee894e818a3aa55ce47571e336304d/src/main/java/org/microbean/jersey/netty/cdi/JerseyNettyExtension.java#L418-L426
I note we don't zero out the shutdown latch, but that may be on purpose, i.e. the assertion may be incorrect.

**Comment by ljnelson** [comment]
That turned out to be quite complicated.  Fixed by https://github.com/microbean/microbean-jersey-netty-cdi/commit/5100396ed1807a3e840d1ef4d6c51bdbb895bab7.
